name: "\u2728 기능 설계 제안"
description: 새로운 기능의 설계 아이디어를 제안합니다.
title: "\u2728 설계: "
labels: ["design", "discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## \u2728 기능 설계 제안

        새로운 기능에 대한 설계 아이디어를 아래 항목에 따라 작성해주세요.
  - type: textarea
    id: user_story
    attributes:
      label: 사용자 스토리
      description: 기능의 필요성을 사용자 관점에서 설명해주세요.
      placeholder: |
        예: "As a [사용자 유형], I want [기능] so that [이유]."
    validations:
      required: true
  - type: textarea
    id: problem_statement
    attributes:
      label: 문제 설명
      description: 현재 시스템에서 발생하는 문제나 충족되지 않는 요구사항을 구체적으로 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: 제안된 해결 방안
      description: 문제를 해결하기 위한 구체적인 아이디어나 제안을 작성해주세요.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 대안 고려 사항
      description: 다른 해결 방안이나 접근 방법을 고려했는지, 그리고 왜 제안된 해결 방안을 선택했는지를 설명해주세요.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: 추가 정보
      description: 관련된 문서, 링크, 스크린샷 등을 포함하여 이슈를 이해하는 데 도움이 되는 추가 정보를 제공해주세요.
    validations:
      required: false
