name: PR Changed Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      unit_files: ${{ steps.filter.outputs.unit_files }}
      integration_files: ${{ steps.filter.outputs.integration_files }}
      e2e_files: ${{ steps.filter.outputs.e2e_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            unit:
              - added|modified: 'tests/unit/**'
              - regex: '^tests/unit/.*/test_.*\.py$'
            integration:
              - added|modified: 'tests/integration/**'
              - regex: '^tests/integration/.*/test_.*\.py$'
            e2e:
              - added|modified: 'tests/e2e/**'
              - regex: '^tests/e2e/.*/test_.*\.py$'

  unit-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.unit_files != '[]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test TEST_SCOPE=unit TEST_TARGETS="${{ join(fromJson(needs.detect-changes.outputs.unit_files), ' ') }}"

  integration-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.integration_files != '[]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test TEST_SCOPE=integration TEST_TARGETS="${{ join(fromJson(needs.detect-changes.outputs.integration_files), ' ') }}"

  e2e-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.e2e_files != '[]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test TEST_SCOPE=e2e TEST_TARGETS="${{ join(fromJson(needs.detect-changes.outputs.e2e_files), ' ') }}"