name: CI - Pull Request Test

on:
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      unit_files: ${{ steps.filter.outputs.unit_files }}
      integration_files: ${{ steps.filter.outputs.integration_files }}
      e2e_files: ${{ steps.filter.outputs.e2e_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          base: origin/${{ github.base_ref }}
          filters: |
            unit:
              - added|modified: 'tests/unit/**'
              - regex: '^tests/unit/.*/test_.*\.py$'
            integration:
              - added|modified: 'tests/integration/**'
              - regex: '^tests/integration/.*/test_.*\.py$'
            e2e:
              - added|modified: 'tests/e2e/**'
              - regex: '^tests/e2e/.*/test_.*\.py$'

  run-unit-tests:
    if: ${{ needs.detect-changes.outputs.unit_files != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Run unit tests
        env:
          UNIT_TEST_PATHS: ${{ needs.detect-changes.outputs.unit_files }}
        run: |
          docker compose -f docker/test/compose.unit.yml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from unit-test
    
  run-integration-tests:
    if: ${{ needs.detect-changes.outputs.integration_files != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run integration tests
        env:
          INTEGRATION_TEST_PATHS: ${{ needs.detect-changes.outputs.integration_files }}
        run: |
          docker compose -f docker/test/compose.integration.yml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from integration-test

  run-e2e-tests:
    if: ${{ needs.detect-changes.outputs.e2e_files != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run e2e tests
        env:
          E2E_TEST_PATHS: ${{ needs.detect-changes.outputs.e2e_files }}
        run: |
          docker compose -f docker/test/compose.e2e.yml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from e2e-test
